# Generated by Django 5.1.7 on 2025-03-15 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity_source_count_type',
            field=models.CharField(blank=True, choices=[('pc', 'PC (Workstations & Laptops)'), ('server', 'Servers'), ('employee', 'Employees'), ('sites', 'Sites / Branches / Locations'), ('switches', 'Network Switches'), ('phones', 'Phones'), ('tablets', 'Tablets (iPad, Android)'), ('vpn', 'VPN Users')], help_text='Count type to pull quantity from (e.g., pc, server)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='count_type',
            field=models.CharField(blank=True, choices=[('pc', 'PC (Workstations & Laptops)'), ('server', 'Servers'), ('employee', 'Employees'), ('sites', 'Sites / Branches / Locations'), ('switches', 'Network Switches'), ('phones', 'Phones'), ('tablets', 'Tablets (iPad, Android)'), ('vpn', 'VPN Users')], help_text='Type of count this question gathers', max_length=100, null=True),
        ),
    ]
