# Generated by Django 5.1.7 on 2025-03-15 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_alter_product_quantity_source_count_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='help_resources/')),
                ('external_link', models.URLField(blank=True, null=True)),
                ('type', models.CharField(choices=[('video', 'Video'), ('audio', 'Audio'), ('pdf', 'PDF'), ('link', 'External Link')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StandardizedInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='conditional_on',
        ),
        migrations.RemoveField(
            model_name='question',
            name='conditional_value',
        ),
        migrations.RemoveField(
            model_name='question',
            name='quantity_source_question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='recommend_if_unknown',
        ),
        migrations.RemoveField(
            model_name='question',
            name='recommend_if_yes',
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('yes_no', 'Yes/No/Other'), ('multiple_choice', 'Multiple Choice'), ('input', 'Input')], max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='recommended_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assessment.product'),
        ),
        migrations.AddField(
            model_name='question',
            name='help_resources',
            field=models.ManyToManyField(blank=True, help_text='Optional help resources for users', to='assessment.helpresource'),
        ),
        migrations.AddField(
            model_name='question',
            name='standardized_inputs',
            field=models.ManyToManyField(blank=True, help_text='Select standardized answers to show for this question', to='assessment.standardizedinput'),
        ),
    ]
