# Generated by Django 5.1.7 on 2025-03-15 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0003_helpresource_standardizedinput_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='audio_url',
        ),
        migrations.RemoveField(
            model_name='question',
            name='pdf_url',
        ),
        migrations.RemoveField(
            model_name='question',
            name='video_url',
        ),
        migrations.AddField(
            model_name='question',
            name='audio',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'audio'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audio_questions', to='assessment.helpresource'),
        ),
        migrations.AddField(
            model_name='question',
            name='pdf',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'pdf'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pdf_questions', to='assessment.helpresource'),
        ),
        migrations.AddField(
            model_name='question',
            name='video',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'video'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_questions', to='assessment.helpresource'),
        ),
    ]
