# Generated by Django 5.1.7 on 2025-03-18 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0004_remove_question_audio_url_remove_question_pdf_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSVUploadPlaceholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Upload Questions CSV',
                'verbose_name_plural': 'Upload Questions CSV',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order']},
        ),
        migrations.AlterField(
            model_name='category',
            name='order',
            field=models.IntegerField(default=0, verbose_name='something'),
        ),
        migrations.AlterField(
            model_name='helpresource',
            name='external_link',
            field=models.URLField(blank=True, help_text='Enter a YouTube video URL if applicable', null=True),
        ),
    ]
