# Generated by Django 5.1.7 on 2025-03-29 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0005_csvuploadplaceholder_alter_question_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='selected_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assessment.standardizedinput'),
        ),
    ]
