# Generated by Django 5.1.7 on 2025-03-30 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0006_alter_useranswer_selected_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardizedinput',
            name='is_preferred',
            field=models.BooleanField(default=False),
        ),
    ]
