# Generated by Django 5.1.7 on 2025-03-30 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0007_standardizedinput_is_preferred'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='standardized_inputs',
        ),
        migrations.RemoveField(
            model_name='standardizedinput',
            name='is_preferred',
        ),
        migrations.CreateModel(
            name='QuestionInputOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_value', models.IntegerField(default=0)),
                ('is_preferred', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_options', to='assessment.question')),
                ('standardized_input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.standardizedinput')),
            ],
            options={
                'unique_together': {('question', 'standardized_input')},
            },
        ),
        migrations.DeleteModel(
            name='QuestionOption',
        ),
    ]
